[build]
  command = "echo 'Build command goes here'"
  publish = "/"

[functions]
  directory = "netlify/functions/"
  # Perpanjang batas waktu eksekusi fungsi menjadi 26 detik
  # (batas maksimal untuk paket gratis)
  timeout = 26 

[[plugins]]
  # Plugin ini akan secara otomatis meng-install dependensi 
  # yang ada di package.json di dalam folder functions
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

