# Konfigurasi ini memberitahu Netlify cara menangani request
# untuk aplikasi berbasis JavaScript seperti React.

[build]
  # Direktori tempat fungsi serverless Anda berada
  functions = "netlify/functions"

[[redirects]]
  # Arahkan semua request yang tidak cocok dengan file yang ada
  # ke fungsi 'gemini' kita. Ini penting agar API call berfungsi.
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  # Aturan ini untuk memastikan routing di sisi client berjalan benar.
  # Semua path URL akan diarahkan ke index.html.
  from = "/*"
  to = "/index.html"
  status = 200
