# Konfigurasi dasar untuk build
[build]
  functions = "netlify/functions"

# Menambahkan plugin untuk install dependensi functions secara otomatis
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Aturan redirect agar request ke /api/gemini diteruskan ke function kita
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

