[build]
  functions = "netlify/functions"

# Menambahkan blok ini untuk meningkatkan batas waktu
[functions]
  timeout = 26 # Waktu dalam detik (maksimal untuk sinkron)

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

